name: C Program Test and Bug Tracking

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-c:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile C programs
      run: |
        gcc 0x00-hello_world/4-puts.c -o 0x00-hello_world/4-puts
        gcc 0x00-hello_world/5-printf.c -o 0x00-hello_world/5-printf

    - name: Make test scripts executable
      run: chmod +x 0x00-hello_world/tests/*.sh

    - name: Run tests
      id: run_tests
      run: |
        cd 0x00-hello_world/tests
        ./run_all_tests.sh | tee test_output.txt
        echo "exit_code=${PIPESTATUS[0]}" >> $GITHUB_ENV

    - name: Report bugs if any tests fail
      if: env.exit_code != '0'
      run: |
        TEST_OUTPUT=$(cat 0x00-hello_world/tests/test_output.txt)
        FAILED_TESTS=$(grep "FAIL" 0x00-hello_world/tests/test_output.txt | tr '\n' ',' | sed 's/,$//' || echo "Unknown failure")
        FAILURE_COUNT=$(grep -c "FAIL" 0x00-hello_world/tests/test_output.txt || echo "0")
        BUG_TITLE="URGENT: $FAILURE_COUNT Test Failures in ${{ github.repository }} on $(date '+%Y-%m-%d %H:%M:%S')"
        ENCODED_OUTPUT=$(echo "$TEST_OUTPUT" | base64 -w 0)
        BUG_TRACKER_API="https://zspnb989-3000.uks1.devtunnels.ms/api/ci-report"

        curl -X POST "$BUG_TRACKER_API" \
          -H "Content-Type: application/json" \
          -H "Azure-DevTunnel-Bypass: 1" \
          -H "Authorization: Bearer ${{ secrets.BUG_TRACKER_API_KEY }}" \
          -d "{
            \"projectId\": \"${{ secrets.BUG_TRACKER_PROJECT_ID }}\",
            \"commit\": \"${{ github.sha }}\",
            \"branch\": \"${{ github.ref_name }}\",
            \"repository\": \"${{ github.repository }}\",
            \"bugTitle\": \"$BUG_TITLE\",
            \"testOutput\": \"$ENCODED_OUTPUT\",
            \"failedTests\": \"$FAILED_TESTS\",
            \"failureCount\": \"$FAILURE_COUNT\"
          }" 2>&1 | grep -v "Authorization"
